language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
script:
  - npm run build
deploy:
  provider: npm
  email: james.hrisho@gmail.com
  api_key:
    secure: NAaETCUEyK/SxJIv8vcX3RjCSoY5FYEcwVHgU/102IqfTiqQZFSjvN24odEdYE4AqaxRhefhywxDuSZ5oF9hlcmRb/cjf0mbPSdxifS1SIYAHO7WTmIYs380weXTItRu8u54nkX35yPSWUdnORnl2rowtpK3MDr/Y9Jsbss80Zo=
  skip_cleanup: true
  on:
    tags: true
    repo: securingsincity/react-ace
